### PR TITLE
add option to hide progress bar

### PR DESCRIPTION
**Pull request by bbelderbos**
@jeffwright13 I'd like to use this awesome tool for `pybites-alarm` (https://github.com/PyBites-Open-Source/pybites-alarm/pull/7) but the progress bar is a bit cluttering in that case so I'd like to call it like this:

```
kwargs = {"hide_progress_bar": True}
apg = AudioProgramGenerator(StringIO(alarm_text), **kwargs)
```

Should be a non disruptive change as progress bar will show by default.

Is that ok with you?

### CODE REVIEW

**Comment by jeffwright13** [comment]
Sure, should be OK. I will test it out when I get back home from weekend vacation.

**Comment by bbelderbos** [comment]
Awesome, thanks. Really cool package, works nicely with the alarm tool :)

**Comment by bbelderbos** [comment]
Thanks will you make a new release on PyPI?

**Comment by jeffwright13** [comment]
I will as soon as possible. I also want to bail on poetry and go back to
setup.py and requirements.txt. I cannot for the life of me figure out the
poetry workflow.

**Comment by bbelderbos** [comment]
Yeah I like `poetry` but sometimes it's doing too much :)
Maybe you want to use `flit`, then you can still use the new toml file format: https://www.youtube.com/watch?v=Stu-8MsTAu8

**Pull request merged**
